# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
      inputs.chaotic.nixosModules.default
    ];

  #boot.kernelPackages = pkgs.linuxPackages_6_17;
  nixpkgs.config.rocmSupport = true;


  #boot.kernelPackages = pkgs.linuxPackages_cachyos-lto;
  boot.kernelPackages = pkgs.linuxPackages_zen;

  # Enable BORE scheduler
  boot.kernel.sysctl."kernel.sched_bore" = 1;

  # Set Kyber as default I/O scheduler
  hardware.block.defaultScheduler = "kyber";  

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "amdgpu" ];
  boot.extraModulePackages = [ ];

  system.autoUpgrade = {
    enable = false;
  };


  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      rocmPackages.clr.icd       # ROCm OpenCL
      rocmPackages.clr           # ROCm runtime
      rocmPackages.rocm-runtime  # Additional runtime
    ];
  };


  services.xserver.videoDrivers = [ "amdgpu" ];


  # Required for OpenCL ICD loader
  environment.systemPackages = with pkgs; [
    clinfo
    rocmPackages.rocminfo
  ];

  services.tlp = {
    enable = false;
    settings = {
      START_CHARGE_THRESH_BAT0 = 75;  # Start charging at 75%
      STOP_CHARGE_THRESH_BAT0 = 80;   # Stop charging at 80%
    };
  };

  services.power-profiles-daemon.enable = true;

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/6638ca69-8a70-4f82-afd6-02c0d61f4d9f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/2f7b0c1c-5d7f-403f-b4fd-fc0f423e83ee";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/B01C-E401";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [
    {
      device = "/swapfile";
      size = 64 * 1024; # 16GB
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp194s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
